import React from 'react'
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from "@/components/ui/accordion"


function Faq() {
    return (
        <div className='bg-gray-100 pt-8 pb-8'>
            <h1 className='my-8 font-semibold font-sans text-center text-4xl'>FAQ</h1>
            <div className='flex justify-center items-center mb-8 mx-4'>
            <Accordion type="single" collapsible className='md:w-1/2'>
                <AccordionItem value="item-1">
                    <AccordionTrigger >What is Kahani?</AccordionTrigger>
                    <AccordionContent>
                    Kahani is an AI Story Generator that utilizes artificial intelligence to create compelling and original stories for young childrens based on Input.
                    </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-2">
                    <AccordionTrigger>Are the stories generated by Kahani safe for children?</AccordionTrigger>
                    <AccordionContent>
                    Yes, all stories generated by Kahani are carefully crafted to be safe and appropriate for children. We prioritize child-friendly content, ensuring that the stories are free from violence, inappropriate language, and adult themes.
                    </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-3">
                    <AccordionTrigger>Can stories be saved and shared?</AccordionTrigger>
                    <AccordionContent>
                    Yes, you can save your child’s favorite stories and share them with friends and family. This feature allows children to revisit their beloved tales and share their creativity with others.
                    </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-4">
                    <AccordionTrigger>Is there a subscription fee for using Kahani?</AccordionTrigger>
                    <AccordionContent>
                    No, Kahani is completely free. You can enjoy unlimited story generation and customization without any cost.
                    </AccordionContent>
                </AccordionItem>
            </Accordion>
            </div>


        </div>
    )
}

export default Faq
